### ISSUE TITLE
nexus browser Android app V1.25 doesn't work

### ISSUE THREAD

**Issue by imalitavakoli** [ionic-team/vscode-ionic#222] opened 2024-12-10 14:03 UTC
Hi,

My Android device updated to the latest version of Nexus app (V1.25). But the app doesn't come up anymore! It crashes each time...
I tested the app in multiple Android devices, but no chance!

Can we have a new fixed version of the app?

Android version that I tested the app in:
12

Thanks a lot,
Ali

**Comment by damiant** [comment] 2024-12-11 00:26
Thanks for the bug report. I can reproduce and should have an update ready shortly.

**Comment by damiant** [comment] 2024-12-11 01:20
This was caused by this [Capacitor Barcode scanner issue](https://github.com/ionic-team/capacitor-barcode-scanner/pull/40) fixed in [v1.04](https://github.com/ionic-team/capacitor-barcode-scanner/blob/main/CHANGELOG.md#102-2024-12-02).
Note: This Nexus Browser repository is located [here](https://github.com/damiant/nexus-browser).

Nexus Browser version 1.26 has been submitted to the Play Store. Expecting approval by 12/11/2024.

**Comment by damiant** [comment] 2024-12-11 13:53
v1.26 is now available in the play store.

**Closed by damiant** 2024-12-11 13:53 UTC
Labels: bug

**Comment by imalitavakoli** [comment] 2025-01-07 12:57
It seems the Nexus Android app (V1.26) didn't implement 'App' plugin!
